---
# defaults file for dotfiles
dotfiles_mpd: false
dotfiles_mpd_music_dir: ~/musics

dotfiles_zsh: false


dotfiles_vim: false

# A list of remote plugin to install, use the default vim packager.
dotfiles_vim_plugin_items: []

# List for zsh plugins to install: e.g - { src: https://xxx, dest: somewhere }
dotfiles_zsh_plugin_items: []

# list of symbolink link to create
dotfiles_zsh_plugin_link_items: []
