---
- name: Alsa > uninstalling conflicting packages
  become: true
  ansible.builtin.package:
    name: "{{ dotfiles_alsa_pkg_conflict_items }}"
    state: absent
  when: dotfiles_alsa_pkg_conflict_items is defined and dotfiles_alsa_pkg_conflict_items | length > 0

- name: Alsa > installing dependencies
  become: true
  ansible.builtin.package:
    name: "{{ dotfiles_alsa_pkg_items }}"
    state: present

- name: Alsa > search card name
  ansible.builtin.shell: cat /proc/asound/card*/id | head -1
  register: audio_card
  check_mode: false
  changed_when: false

- name: Alsa > setting the default card {{ audio_card.stdout }}
  ansible.builtin.set_fact:
    alsa_card: "{{ audio_card.stdout }}"
  when: audio_card.stdout != ''

- name: Alsa > creating config dir for pipewire
  become: true
  ansible.builtin.file:
    path: /etc/alsa/conf.d
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Alsa > creating link files for pipewire
  become: true
  ansible.builtin.file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  loop: "{{ dotfiles_alsa_link_items }}"
  when: dotfiles_alsa_link_items is defined

- name: Alsa > disabling conflicting user services
  become: false
  ansible.builtin.systemd_service:
    name: "{{ item }}"
    state: stopped
    enabled: false
    scope: user
  with_items:
    - pulseaudio.socket
    - pulseaudio.service
  when: ansible_facts["service_mgr"] == "systemd"

- name: Alsa > enabling Wireplumber systemd service for user
  become: false
  ansible.builtin.systemd_service:
    name: "{{ item }}"
    state: started
    enabled: yes
    scope: user
  with_items:
    - pipewire
    - wireplumber
  when: ansible_facts["service_mgr"] == "systemd"

# TODO: add steps on openrc, runnit...

- name: Alsa > adding user to group
  become: true
  ansible.builtin.user:
    name: "{{ ansible_facts['user_id'] }}"
    groups: "{{ dotfiles_alsa_group_items }}"
    append: true
  when: dotfiles_alsa_group_items is defined
