---
- import_tasks: xorg.yml

- name: awm > installing dependencies
  ansible.builtin.package:
    - name: '{{ item }}'
      state: present
  with_items: '{{ dotfiles_awm_pkg_items }}'

- name: awm > add config files using stow
  ansible.builtin.shell: 'stow -d {{ dotfiles_stow_dir }} -Rt ~/ {{ dotfiles_awm_stow_dir }}'
  when: dotfiles_stow_dir is defined and dotfiles_awm_stow_dir is defined
