---
- name: awm > search previous awm3 theme
  ansible.builtin.command: cat /tmp/awm-m3
  ignore_errors: true
  register: previous_theme

- name: awm > setting awm_theme to previous_theme
  ansible.builtin.set_fact:
    awm_theme: '{{ previous_theme.stdout | trim }}'
  when: previous_theme is succeeded

- name: awm > removing awm3 theme {{ awm_theme }}
  ansible.builtin.shell: 'stow -d {{ dotfiles_stow_dir }}/{{ dotfiles_awm_m3_stow_dir_theme }} -Dt ~/ {{ awm_theme }}'
  when:
    - dotfiles_stow_dir_theme is defined
    - dotfiles_awm_m3_stow_dir_theme is defined
    - awm_theme is defined

- name: awm > removing awm3 config
  ansible.builtin.shell: 'stow -d {{ dotfiles_stow_dir }} -Dt ~/ {{ dotfiles_awm_m3_stow_dir }}'
  when: dotfiles_stow_dir is defined and dotfiles_awm_m3_stow_dir is defined
