---
- name: doom-emacs > installing dependencies
  become: true
  ansible.builtin.package:
    name: '{{ dotfiles_emacs_pkg_items }}'
    state: present
  when: dotfiles_emacs_pkg_items is defined

- name: doom-emacs > ensure font directory exist
  ansible.builtin.file:
    path: '{{ dotfiles_external_font_dir }}'
    state: directory

# https://github.com/doomemacs/doomemacs#install
- include_tasks: get-tar.yml
  loop:
    - name: .emacs.d
      url: https://github.com/doomemacs/doomemacs/archive/refs/heads/master.tar.gz
  loop_control:
    loop_var: tar_item
  vars:
    to_dest: '{{ ansible_user_dir }}'

- name: doom-emacs > x doom sync x
  ansible.builtin.command: ~/.emacs.d/bin/doom sync

# https://github.com/domtronn/all-the-icons.el/tree/master/fonts
- name: doom-emacs > get fonts for all-the-icons.el
  ansible.builtin.get_url:
    url: '{{ item }}'
    dest: '{{ dotfiles_external_font_dir }}/{{ item | basename }}'
  with_items:
    - https://raw.githubusercontent.com/domtronn/all-the-icons.el/master/fonts/all-the-icons-project.json
    - https://github.com/domtronn/all-the-icons.el/raw/master/fonts/all-the-icons.ttf
    - https://github.com/domtronn/all-the-icons.el/raw/master/fonts/file-icons.ttf
    - https://github.com/domtronn/all-the-icons.el/raw/master/fonts/fontawesome.ttf
    - https://github.com/domtronn/all-the-icons.el/raw/master/fonts/material-design-icons.ttf
    - https://github.com/domtronn/all-the-icons.el/raw/master/fonts/octicons.ttf
    - https://github.com/domtronn/all-the-icons.el/raw/master/fonts/weathericons.ttf
