---
- name: doom-emacs > removing conflicting packages
  become: true
  ansible.builtin.package:
    name: '{{ dotfiles_emacs_pkg_conflict_items }}'
    state: absent
  when: dotfiles_emacs_pkg_conflict_items is defined

- name: doom-emacs > installing dependencies
  become: true
  ansible.builtin.package:
    name: '{{ dotfiles_emacs_pkg_items }}'
    state: present
  when: dotfiles_emacs_pkg_items is defined

- name: doom-emacs > clean older install
  ansible.builtin.file:
    path: '{{ item }}'
    state: absent
  loop:
    - ~/.emacs.d
    - '{{ dotfiles_external_font_dir }}/all-the-icons-project.json'
    #- '{{ dotfiles_external_font_dir }}/all-the-icons.ttf'
    #- '{{ dotfiles_external_font_dir }}/file-icons.ttf'
    #- '{{ dotfiles_external_font_dir }}/fontawesome.ttf'
    #- '{{ dotfiles_external_font_dir }}/material-design-icons.ttf'
    #- '{{ dotfiles_external_font_dir }}/octicons.ttf'
    #- '{{ dotfiles_external_font_dir }}/weathericons.ttf'
