---
- name: external > installing dependencies
  become: true
  ansible.builtin.package:
    name: unzip
    state: present

- name: external > create font dir
  ansible.builtin.file:
    path: "{{ dotfiles_external_font_dir }}"
    state: directory

- name: external > removing windows font
  ansible.builtin.command: "find {{ dotfiles_external_font_dir}} -name '*Windows*' -delete"

- name: external > removing older fonts
  ansible.builtin.file:
    path: "{{ dotfiles_external_font_dir }}/{{ item }}"
    state: absent
  loop:
    - CyberPunk
    - MaterialDesign
    - material-design
    - MaterialDesign-Font-master
    - Iosevka
    - Iosevka-2.1.0
    - Iosevka-2.1.0.zip
    - SpaceMono
    - SpaceMono-2.1.0
    - SpaceMono-2.1.0.zip

- name: external > updating fonts cache
  ansible.builtin.command: "fc-cache -f {{ dotfiles_external_font_dir}}"
