---
- name: Kew > removing conflicting packages
  become: true
  ansible.builtin.package:
    name: "{{ dotfiles_kew_pkg_conflict_items }}"
    state: absent
  when: dotfiles_kew_pkg_conflict_items is defined

- name: Kew > installing
  become: true
  ansible.builtin.package:
    name: "{{ dotfiles_kew_pkg_items }}"
    state: present
  when: dotfiles_kew_pkg_items is defined
