---
- name: shell > installing {{ dotfiles_shell_pkgname }}
  become: true
  ansible.builtin.package:
    name: '{{ dotfiles_shell_pkgname }}'
    state: present

- name: shell > applying default shell {{ dotfiles_shell_path }} for {{ ansible_user_id }}
  become: true
  ansible.builtin.user:
    name: '{{ username }}'
    shell: '{{ dotfiles_shell_path }}'

- name: shell > get plugins
  ansible.builtin.unarchive:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    remote_src: yes
  with_items: '{{ dotfiles_shell_plugin_items }}'
  when: dotfiles_shell_plugin_items | length > 0

- name: shell > make symbolink links
  ansible.builtin.file:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    state: link
  with_items: '{{ dotfiles_shell_plugin_link_items }}'
  when: dotfiles_shell_plugin_link_items | length > 0
