---
- name: vifm > installing dependencies
  become: true
  ansible.builtin.package:
    name: '{{ dotfiles_vifm_pkg_items }}'
    state: present
  when: dotfiles_vifm_pkg_items is defined

- name: vifm > create required directory ~/bin, ~/.config/vifm/scripts
  ansible.builtin.file:
    path: '{{ item }}'
    state: directory
  with_items:
    - ~/.config/vifm/scripts
    - ~/bin
