---
- name: vifm > installing dependencies
  become: true
  ansible.builtin.package:
    name: '{{ dotfiles_vifm_pkg_items }}'
    state: present
  when: dotfiles_vifm_pkg_items is defined

- name: vifm > create required directory ~/bin, ~/.config/vifm/scripts
  ansible.builtin.file:
    path: '{{ item }}'
    state: directory
  with_items:
    - ~/.config/vifm/scripts
    - ~/bin

- name: vifm > downloading and install epub-thumbnailer.py
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/marianosimone/epub-thumbnailer/master/src/epub-thumbnailer.py
    dest: ~/bin/epub-thumbnailer
    mode: 0700
    use_netrc: false

- name: vifm > install dots with stow
  ansible.builtin.command: 'stow -d {{ dotfiles_stow_dir }} -Rt ~/ {{ dotfiles_vifm_stow_dir }}'
  when: dotfiles_stow_dir is defined and dotfiles_vifm_stow_dir is defined
