---
# https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=xst
- name: xst > installing dependencies for Arch
  community.general.pacman:
    name:
      - libxft
      - ncurses
      - libxext
      - git
  when: ansible_os_family == 'Archlinux'

- name: xst > installing via your package manager
  become: true
  ansible.builtin.package:
    name: '{{ dotfiles_xst_pkg }}'
    state: present
  when: dotfiles_xst_pkg is defined

- name: xst > downloading last sources package
  ansible.builtin.get_url:
    url: 'https://github.com/gnotclub/xst/archive/master.tar.gz'
    dest: '{{ dotfiles_cache_dir}}/xst-{{ dotfiles_xst_version }}.tar.gz'
  register: xst_src
  when: dotfiles_xst_pkg is not defined

- import_tasks: xst-debian.yml
  when: ansible_os_family == 'Debian' and xst_src.changed

- name: nuke build destination
  ansible.builtin.file:
    path: '{{ dotfiles_cache_dir }}/build'
    state: absent
