---
- name: xst > allowing masking keyword
  become: true
  ansible.builtin.copy:
    dest: /etc/portage/package.accept_keywords/xst
    content: =x11-terms/xst-9999 **
  when: ansible_os_family == 'Gentoo'

- name: xst > installing via your package manager
  become: true
  ansible.builtin.package:
    name: '{{ dotfiles_xst_pkg }}'
    state: present
  when: dotfiles_xst_pkg is defined

- import_tasks: xst-debian.yml
  when: ansible_os_family == 'Debian'

- include_tasks: arch-aur.yml
  loop:
    - { name: xst-git,
        deps: [base-devel, libxft, ncurses, libxext, git]
      }
  loop_control:
    loop_var: aur_item
  when: ansible_os_family == 'Archlinux'

- name: nuke build destination
  ansible.builtin.file:
    path: '{{ dotfiles_cache_dir }}/build'
    state: absent
