---
dotfiles_alsa_pkg_conflict_items:
  - pipewire-pulse
  - pulseaudio
dotfiles_alsa_pkg_items:
  - alsa-utils
  - alsa-plugins # speexrate resampling

dotfiles_zsh_path: /usr/bin/zsh
dotfiles_zsh_pkgname: zsh

dotfiles_vim_pkgname_conflict: vim
dotfiles_vim_pkgname: gvim
