---
dotfiles_alsa_pkg_conflict_items:
  - pipewire-pulse
  - pulseaudio

dotfiles_alsa_pkg_items:
  - alsa-utils
  - alsa-plugins # speexrate resampling

dotfiles_awm_pkg_items:
  - awesome
  - picom
  - feh
  - papirus-icon-theme
  - xss-lock
  - inotify-tools
  - scrot

dotfiles_awm3_pkg_items:
  - awesome
  - picom
  - feh
  - papirus-icon-theme
  - xss-lock
  - inotify-tools
  - maim
  - jq
  - curl

dotfiles_betterlockscreen_conflict_pkg_items:
  - i3lock
  - i3lock-color-git

dotfiles_emacs_pkg_conflict_items:
  - emacs
  - emacs-wayland

# https://www.flycheck.org/en/latest/languages.html#flycheck-languages
dotfiles_emacs_pkg_items:
  - ripgrep
  - jq
  - fd
  - rubocop # ruby lint
  - shellcheck # shell lint
  - tidy # html lint
  - stylelint-config-recommended # css lint
  - luacheck # lua lint
  - emacs-nativecomp

dotfiles_files_browser_alsa_pkg_items:
  - thunar
  - tumbler # display image in thunar

dotfiles_files_browser_pulse_pkg_items:
  - nemo

dotfiles_files_browser_conflict_pkg_items:
  - bat
  - ffmpegthumbnailer
  - ueberzug
  - vifm
  - w3m

dotfiles_files_browser_pkg_items:
  - mpv
  - nnn
  - zathura
  - zathura-pdf-mupdf

dotfiles_gpu_intel_gen7_conflict_pkg_items:
  - mesa

# intel https://wiki.archlinux.org/title/Intel_graphics
# https://wiki.archlinux.org/title/Hardware_video_acceleration
dotfiles_gpu_intel_gen7_pkg_items:
  - mesa-amber
  - libva-intel-driver

# Intel gen8 and more
dotfiles_gpu_intel_pkg_items:
  - mesa
  - intel-media-driver
  - vulkan-intel

dotfiles_gpu_nouveau_conflict_pkg_items:
  - nvidia-390xx-dkms
  - nvidia

dotfiles_gpu_nouveau_pkg_items:
  - mesa
  - mesa-vdpau
  - libva-mesa-driver
  - xf86-video-nouveau

dotfiles_mpd_pkg_items:
  - mpd
  - mpc
  - ncmpcpp

dotfiles_neomutt_pkg_conflict_items:
  - mutt
  - msmtp-mta
  - msmtp
  - fdm

dotfiles_neomutt_pkg_items:
  - neomutt
  - isync

dotfiles_neovim_conflict_pkg_items:
  - vim
  - gvim

dotfiles_neovim_pkg_items:
  - neovim
  - fzf
  - tmux
  - fd
  - ripgrep
  - prettier
  - rubocop
  - stylua

dotfiles_pulseaudio_pkg_items:
  - pulseaudio

dotfiles_swayfx_conflict_pkg_items:
  - sway
  - sway-git
  - scenefx-git
  - eww-git

dotfiles_swayfx_pkg_items:
  - papirus-icon-theme
  - inotify-tools
  - imv
  - jq
  - wl-clipboard
  - curl
  - bc
  - imagemagick
  - rubygems
  - grim
  - swaybg
  - wmenu
  - playerctl
  - mpd-mpris
  - mpv-mpris
  - rust
  - git
  - meson
  - scdoc
  - wayland-protocols
  - cairo
  - gdk-pixbuf2
  - libevdev
  - libinput
  - json-c
  - libgudev
  - wayland
  - libxcb
  - libxkbcommon
  - pango
  - pcre
  - wlroots0.17
  - libdrm
  - libglvnd
  - pixman
  - glslang
  - meson
  - ninja
  - cargo
  - libdbusmenu-gtk3
  - gtk3
  - gtk-layer-shell
  - iwd
  - seatd

dotfiles_swayfx_add_to_group:
  - network
  - seat

dotfiles_swayfx_services:
  - seatd

dotfiles_wezterm_pkg_items:
  - wezterm

dotfiles_xorg_pkg_items:
  - xorg-server
  - xorg-xinit
  - xclip
  - xf86-input-libinput

dotfiles_zsh_path: /usr/bin/zsh
dotfiles_zsh_pkgname: zsh
dotfiles_zsh_pkg_items:
  - zsh
  - starship
  - yt-dlp
