---
dotfiles_alsa_pkg_conflict_items:
  - pulseaudio
dotfiles_alsa_pkg_items:
  - alsa-utils
  - alsa-plugins
  - alsa-plugins-samplerate

dotfiles_zsh_path: /usr/bin/zsh
dotfiles_zsh_pkgname: zsh

dotfiles_vim_pkgname_conflict: vim
dotfiles_vim_pkgname: vim-x11
