---

- include_tasks: arch-aur.yml
  loop:
    - name: librewolf-bin
      deps: [gtk3, libxt, startup-notification, mime-types, dbus-glib,
              nss, ttf-font, libpulse, ffmpeg]
      gpg_key: 031F7104E932F7BD7416E7F6D2845E1305D6E801
      gpg_server: hkp://keyserver.ubuntu.com:80
  loop_control:
    loop_var: aur_item
  when: ansible_os_family == 'Archlinux'

- name: librewolf > importing apt-repo
  become: true
  block:
    - name: librewolf | apt key
      ansible.builtin.get_url:
        url: https://deb.librewolf.net/keyring.gpg
        dest: /etc/apt/trusted.gpg.d/librewolf.asc
        # ansible.builtin.command:
        # wget -O- https://deb.librewolf.net/keyring.gpg | sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/librewolf.asc

    - name: librewolf | apt source
      ansible.builtin.apt_repository:
        repo: deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/librewolf.asc] https://deb.librewolf.net {{ ansible_distribution_release }} main
        filename: librewolf
        update_cache: yes
  when: ansible_os_family == 'Debian'

- name: librewolf > installing dependencies
  become: true
  ansible.builtin.package:
    name: librewolf
    state: present
  when: ansible_os_family != 'Archlinux'
