---
- include_tasks: arch-aur.yml
  loop:
    - name: librewolf-bin
      deps:
        [
          gtk3,
          libxt,
          startup-notification,
          mime-types,
          dbus-glib,
          nss,
          ttf-font,
          libpulse,
          ffmpeg,
        ]
      gpg_key: 031F7104E932F7BD7416E7F6D2845E1305D6E801
      gpg_server: hkp://keyserver.ubuntu.com:80
  loop_control:
    loop_var: aur_item
  when: ansible_os_family == 'Archlinux'

- name: librewolf > importing apt-repo
  become: true
  block:
    - name: librewolf | apt key
      ansible.builtin.shell: |
        [ -f /etc/apt/trusted.gpg.d/librewolf.gpg ] \
          && rm /etc/apt/trusted.gpg.d/librewolf.gpg

        wget -O- https://deb.librewolf.net/keyring.gpg | gpg --dearmor -o /etc/apt/trusted.gpg.d/librewolf.gpg

    - name: librewolf | apt source
      ansible.builtin.apt_repository:
        repo: deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/librewolf.gpg] https://deb.librewolf.net {{ ansible_distribution_release }} main
        filename: librewolf
        update_cache: yes
  when: ansible_os_family == 'Debian'

- name: librewolf > for Gentoo
  become: true
  block:
    - name: LibreWolf Repo
      ansible.builtin.copy:
        src: librewolf.conf
        dest: /etc/portage/repos.conf/librewolf.conf

    - name: LibreWolf Sync
      ansible.builtin.command: emaint -r librewolf sync
  when: ansible_os_family == 'Gentoo'

- name: librewolf > for Void
  become: true
  block:
    - name: LibreWolf Repo
      ansible.builtin.copy:
        src: 20-librewolf.conf
        dest: /etc/xbps.d/20-librewolf.conf

    - name: Add key
      ansible.builtin.lineinfile:
        path: /var/db/xbps/keys
        regexp: "^3d:b9:c0:50:41"
        line: "3d:b9:c0:50:41:a7:68:4c:2e:2c:a9:a2:5a:04:b7:3f.plist"
  when: ansible_os_family == 'Void'

- name: librewolf > installing dependencies
  become: true
  ansible.builtin.package:
    name: "{{ web_browser_librewolf_pkg }}"
    state: present
  when: web_browser_librewolf_pkg is defined
