---
# tasks file for web_browser
#
#
- name: ensure cache dir {{ web_browser_cache_dir }} exist
  ansible.builtin.file:
    path: '{{ web_browser_cache_dir }}'
    state: directory

- import_tasks: brave.yml
  when: web_browser_brave | bool

- import_tasks: librewolf.yml
  when: web_browser_librewolf | bool
