---
# handlers file for dotfiles
- name: emerge changed use
  become: true
  community.general.portage:
    package: '@world'
    changed_use: true
    deep: true

- name: enable systemd mbsync
  ansible.builtin.systemd:
    name: mbsync.timer
    enabled: yes
    state: reloaded
    scope: user
