---
# handlers file for dotfiles
- name: emerge changed use
  become: true
  community.general.portage:
    package: '@world'
    newuse: true
    deep: true
  when: ansible_os_family == 'Gentoo'

- name: enable systemd mbsync
  ansible.builtin.systemd:
    name: mbsync.timer
    enabled: yes
    state: reloaded
    scope: user
