---
- name: sddm > remove conflicting packages
  become: true
  ansible.builtin.package:
    name: '{{ display_manager_sddm_conflict_items }}'
    state: absent
  when: display_manager_sddm_conflict_items is defined

- name: sddm > installing dependencies
  become: true
  ansible.builtin.package:
    name: '{{ display_manager_sddm_pkg_items }}'
    state: present
  notify:
    - remove display-manager link
    - enable sddm

- name: sddm > required user dir
  ansible.builtin.file:
    path: '{{ item }}'
    state: directory
  with_items:
    - '{{ display_manager_cache_dir }}'

- name: sddm > required dir
  become: true
  ansible.builtin.file:
    path: '{{ item }}'
    state: directory
  with_items:
    - '{{ display_manager_sddm_theme_dir }}/{{ display_manager_theme.name }}'
    - '{{ display_manager_sddm_config_dir }}'
  when: display_manager_theme.name != ''

- name: sddm > download the last {{ display_manager_theme.name }} archive
  ansible.builtin.get_url:
    url: '{{ display_manager_theme.url }}'
    dest: '{{ display_manager_cache_dir }}/{{ display_manager_theme.name }}.tar.gz'
    checksum: 'sha256:{{ display_manager_theme.sum }}'
  register: sddm_theme
  when: display_manager_theme.url != '' and display_manager_theme.sum != '' and
    display_manager_theme.name != ''

- name: sddm > uncompressing theme {{ display_manager_theme.name }}
  become: true
  ansible.builtin.unarchive:
    src: '{{ display_manager_cache_dir }}/{{ display_manager_theme.name }}.tar.gz'
    dest: '{{ display_manager_sddm_theme_dir }}/{{ display_manager_theme.name }}'
    extra_opts: [--strip-components=1]
  when: sddm_theme.changed

- name: sddm > download background
  ansible.builtin.get_url:
    url: '{{ display_manager_background.url }}'
    dest: '{{ display_manager_cache_dir }}//sddm-background.tar.gz'
    checksum: 'sha256:{{ display_manager_background.sum }}'
  register: sddm_background
  when: display_manager_background.url != '' and
    display_manager_background.sum != ''

- name: sddm > uncompressing background
  become: true
  ansible.builtin.unarchive:
    src: '{{ display_manager_cache_dir }}/sddm-background.tar.gz'
    dest: '{{ display_manager_sddm_theme_dir }}/{{ display_manager_theme.name }}/{{ display_manager_theme.background_dir }}'
    extra_opts: [--strip-components=1]
  when: sddm_background.changed

- name: sddm > applying config
  become: true
  ansible.builtin.template:
    src: sddm-config.j2
    dest: '{{ display_manager_sddm_config_dir }}/desktop.conf'

- name: sddm > edit theme {{ display_manager_theme.name }}
  become: true
  ansible.builtin.lineinfile:
    path: '{{ display_manager_sddm_theme_dir }}/{{ display_manager_theme.name }}/theme.conf'
    regexp: '^background='
    line: 'background={{ display_manager_background.name }}'
  when: display_manager_theme.name != '' and display_manager_background.name != ''

- name: sddm > customize theme
  become: true
  ansible.builtin.lineinfile:
    path: '{{ display_manager_sddm_theme_dir }}/{{ display_manager_theme.name }}/theme.conf'
    regexp: '{{ item.regexp }}'
    line: '{{ item.line }}'
  with_items: '{{ display_manager_theme_customize }}'
  when: display_manager_theme_customize | length > 0 and display_manager_theme.name != ''
