#!/usr/bin/env sh

WALLS="/usr/share/backgrounds"
TARGET="$WALLS/default.png"

[ -f "$TARGET" ] && rm "$TARGET"

CHOOSE=$(find $WALLS -regex ".*\.\(jpg\|png\)" | shuf -n 1)

if [ "$(file -b --mime-type "$CHOOSE")" = "image/jpeg" ]; then
  magick "$CHOOSE" "$TARGET"
else
  cp "$CHOOSE" "$TARGET"
fi
